#%RAML 1.0 NamedExample
getRoutes:
  [
    {
        "originLocation" : {
            "locationCode" : "BEN-SG"
        },
        "destinationLocation" : {
            "locationCode" : "KLG-MY"
        }
    },
    {
        "originLocation" : {
            "locationCode" : "BEN-SG"
        },
        "destinationLocation" : {
            "locationCode" : "KLG-MY"
        }
    }
]