#%RAML 1.0
title: RetriveFastGoRoutesAndSchedules-SystemAPI
description: This API will fetch Routes and Schedules From FastGo System.

/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        headers:
          transactionId:
            type: string
            required: true
            example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd"
        responses:
          200:
            body:
              application/json:
                example: !include example/getRoutes.raml
          400:
            body:
              application/json:
                example: { "code": "INVALID_PARAMETER", "message": "parameter transportType is missing."}
          404:
            body:
              application/json:
                example: {"message" : "NOT_FOUND"}
          500:
            body:
              application/json:
                example: {"message" : "SERVER_ERROR"}
    /schedules:
      get:
        headers:
          transactionId:
            type: string
            required: true
            example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd" 
        queryParameters:
          departureLocationCode:
            type: string
            required: false
            example: "BEN-SG"
          destinationLocationCode:
            type: string
            required: false
            example: "KLG-MY"
        responses:
          200:
            body:
              application/json:
                example: !include example/getSchedules.raml
          400:
            body:
              application/json:
                example: { "code": "INVALID_PARAMETER", "message": "parameter transportType is missing."}
          404:
            body:
              application/json:
                example: {"message" : "NOT_FOUND"}
          500:
            body:
              application/json:
                example: {"message" : "SERVER_ERROR"}