#%RAML 1.0 NamedExample
getRoutes:
  [
    {
            "departureLocationCode" : "BEN-SG",
            "arrivalLocationCode" : "KLG-MY"
        
    },
    {
        "departureLocationCode" : "BEN-SG",
        "arrivalLocationCode" : "BU-MY"
        
    }
]